# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Admin.create(email: "test@superadmin.com", first_name: "Super", last_name: "Admin", phone_number: "11111111", password: "Pass88!!", password_confirmation: "Pass88!!", admin: true)

hotel_list = [
	["Hilton Garden Inn Napa", "hginapa", "baloon.jpg"],
	["McKinleyville", "mck", "https://www.arcata-eurekahiexpress.com/wp-content/gallery/todo/header_todo2.jpg"],
  ["Corte Madera", "cmi", "cmi_header.jpg"]
]

hotel_list.each do |fullname, shortname, link|
	Hotel.create(fullname: fullname, shortname: shortname, picture_link: link)
end

booking_engine_list = ["Hotels.com", "Priceline.com", "Booking.com", "Expedia.com", "Bookit.com", "Orbitz.com", "Hilton.com", "Agoda.com", "Kayak.com", "Travelocity.com"]

booking_engine_list.each do |url|
	BookingEngine.create(type_: url)
end

room_type_list = [
	[1, "One King 1 Bedroom Suite", "Complimentary WiFi, 42-inch TV, work desk, ergonomic chair, refrigerator, microwave. Enjoy your stay in this inviting guest room, complete with one king bed and convenient amenities. Keep on top of business at the desk with an ergonomic chair, browse online with the complimentary WiFi or entertain yourself with a movie on the 42-inch TV with Direct TV channels. Store and prepare your own snacks with the refrigerator and microwave or make a refreshing beverage with the Keurig® coffeemaker. Special touches include our Stay Fit Kit (available from reception).", "https://secure3.hilton.com/resources/media/gi/APCNHGI/en_US/img/hotel/roomtypeimages/main/GI_stkingrm001_386x310_FitToBoxSmallDimension_Center.jpg"],
	[1, "One King, 1 Bedroom Whirlpool Suite", "Complimentary WiFi, 42-inch TV, work desk, ergonomic chair, refrigerator, microwave. Enjoy your stay in this inviting guestroom, complete with one king bed and convenient amenities. Keep on top of business at the desk with an ergonomic chair, browse online with the complimentary WiFi or entertain yourself with a movie on the 42-inch TV and Direct TV channels.Store and prepare your own snacks with the refrigerator and microwave or make a refreshing beverage with the Keurig® coffeemaker. Special touches include our Stay Fit Kit (available from reception).", "https://secure3.hilton.com/resources/media/gi/APCNHGI/en_US/img/hotel/roomtypeimages/main/GI_kingsuiteliv001_386x310_FitToBoxSmallDimension_Center.jpg"],
	[1, "One King Bed, Whirlpool Suite", "Complimentary WiFi, 42-inch TV, work desk, ergonomic chair, refrigerator, microwave. Enjoy your stay in this inviting guestroom, complete with one king bed and convenient amenities. Keep on top of business at the desk with an ergonomic chair, browse online with the complimentary WiFi or entertain yourself with a movie on the 42-inch TV and Direct TV channels. Store and prepare your own snacks with the refrigerator and microwave or make a refreshing beverage with the Keurig® coffeemaker. Special touches include our Stay Fit Kit (available from reception).", "https://secure3.hilton.com/resources/media/gi/APCNHGI/en_US/img/hotel/roomtypeimages/main/GI_ksuitebed001_386x310_FitToBoxSmallDimension_Center.jpg"],
	[1, "One King Bed, Mobility Accessible with Bathtub", "Complimentary WiFi, 42-inch TV, work desk, ergonomic chair, refrigerator, microwave. Enjoy your stay in this inviting guestroom, complete with one queen bed and convenient amenities. Keep on top of business at the desk with an ergonomic chair, browse online with the complimentary WiFi or entertain yourself with a movie on the 42-inch TV and Direct TV channels. Store and prepare your own snacks with the refrigerator and microwave or make a refreshing beverage with the Keurig® coffeemaker. Special touches include our Stay Fit Kit (available from reception).", "https://secure3.hilton.com/resources/media/gi/APCNHGI/en_US/img/hotel/roomtypeimages/main/GI_ksuitebed001_386x310_FitToBoxSmallDimension_Center.jpg"],
	[1, "Room, 2 Queen Beds, Accessible", "Complimentary WiFi, 42-inch TV, work desk, ergonomic chair, refrigerator, microwave. Enjoy your stay in this inviting guestroom, complete with two queen beds and convenient amenities. Keep on top of business at the desk with an ergonomic chair, browse online with the complimentary WiFi or entertain yourself with a movie on the 42-inch TV and Direct TV channels. Store and prepare your own snacks with the refrigerator and microwave or make a refreshing beverage with the Keurig® coffeemaker. Special touches include our Stay Fit Kit (available from reception).", "https://secure3.hilton.com/resources/media/gi/APCNHGI/en_US/img/hotel/roomtypeimages/main/GI_dblqnrm001_386x310_FitToBoxSmallDimension_Center.jpg"],
	[1, "One King, Whirlpool Accessible Suite", "Complimentary WiFi, 42-inch TV, work desk, ergonomic chair, refrigerator, microwave. Enjoy your stay in this inviting guestroom, complete with one king bed and convenient amenities. Keep on top of business at the desk with an ergonomic chair, browse online with the complimentary WiFi or entertain yourself with a movie on the 42-inch TV and Direct TV channels. Store and prepare your own snacks with the refrigerator and microwave or make a refreshing beverage with the Keurig® coffeemaker. Special touches include our Stay Fit Kit (available from reception).", "https://secure3.hilton.com/resources/media/gi/APCNHGI/en_US/img/hotel/roomtypeimages/main/GI_kingsuiteliv001_386x310_FitToBoxSmallDimension_Center.jpg"],
	[1, "One King Bed", "Complimentary WiFi, 42-inch TV, work desk, ergonomic chair, refrigerator, microwave. Enjoy your stay in this inviting guestroom, complete with one king bed and convenient amenities. Keep on top of business at the desk with an ergonomic chair, browse online with the complimentary WiFi or entertain yourself with a movie on the 42-inch TV and Direct TV channels. Store and prepare your own snacks with the refrigerator and microwave or make a refreshing beverage with the Keurig® coffeemaker. Special touches include our Stay Fit Kit (available from reception).", "https://secure3.hilton.com/resources/media/gi/APCNHGI/en_US/img/hotel/roomtypeimages/main/GI_stkingrm001_386x310_FitToBoxSmallDimension_Center.jpg"],
	[1, "Suite, 2 Queen Beds, Accessible", "Complimentary WiFi, 42-inch TV, work desk, ergonomic chair, refrigerator, microwave. Enjoy your stay in this inviting guestroom, complete with two queen beds and convenient amenities. Keep on top of business at the desk with an ergonomic chair, browse online with the complimentary WiFi or entertain yourself with a movie on the 42-inch TV and Direct TV channels. Store and prepare your own snacks with the refrigerator and microwave or make a refreshing beverage with the Keurig® coffeemaker. Special touches include our Stay Fit Kit (available from reception).", "https://secure3.hilton.com/resources/media/gi/APCNHGI/en_US/img/hotel/roomtypeimages/main/GI_dblqnrm001_386x310_FitToBoxSmallDimension_Center.jpg"],
	[1, "Two Queen Beds", "Complimentary WiFi, 42-inch TV, work desk, ergonomic chair, refrigerator, microwave. Enjoy your stay in this inviting guestroom, complete with two queen beds and convenient amenities. Keep on top of business at the desk with an ergonomic chair, browse online with the complimentary WiFi or entertain yourself with a movie on the 42-inch TV and Direct TV channels. Store and prepare your own snacks with the refrigerator and microwave or make a refreshing beverage with the Keurig® coffeemaker. Special touches include our Stay Fit Kit (available from reception).", "https://secure3.hilton.com/resources/media/gi/APCNHGI/en_US/img/hotel/roomtypeimages/main/GI_dblqnrm001_386x310_FitToBoxSmallDimension_Center.jpg"],
	[2, "King Whirlpool Suites", "Opt for extra romance with our hotel’s King Whirlpool Suite. These spacious rooms include an expanded seating area, and a wet bar, as well as a spa tub for two and comfy terry cloth robes.", "https://www.arcata-eurekahiexpress.com/wp-content/uploads/2015/06/MKVCA-HIEX-Arcata-Eureka-King_Jacuzzi_Suite002-1024x683.jpg"],
	[2, "King Suites", "Our spacious King Suites offer lots of special features and are great for extended stays and families. Amenities include expanded seating area with sofa and a hospitality center with a microwave, refrigerator and sink.", "https://www.arcata-eurekahiexpress.com/wp-content/uploads/2015/06/MKVCA-HIEX-Arcata-Eureka-Standard_Junior_King_Suite_001-1024x683.jpg"],
	[2, "King Rooms", "King Rooms are perfect for business travelers wanting a dedicated work space. Amenities include a king bed, comfortable chair and ottoman, and a work desk with office chair.", "https://www.arcata-eurekahiexpress.com/wp-content/uploads/2015/06/MKVCA-HIEX-Arcata-Eureka-Standard_King_002-1024x683.jpg"],
	[2, "Double Queen Room", "Our Double Queen Rooms feature two queen beds and a table with two comfy chairs. These rooms are a great, affordable option for families or friends traveling together.", "https://www.arcata-eurekahiexpress.com/wp-content/uploads/2015/06/MKVCA-HIEX-Arcata-Eureka-Standard_Double_001-1024x683.jpg"],
  [3, "Our Executive level king guest rooms offer a king size bed with feather bed and duvet. These spacious rooms include a separate seating area and large work desk perfect for the business traveler", "https://www.cortemaderainn.com/wp-content/uploads/2015/12/DSC_6280.jpg"],
  [3, "Deluxe King Guest Room", "Our deluxe level king guest rooms offer a king size bed with feather bed and duvets. These rooms are spacious and beautifully appointed. Various locations and room designs.", "https://www.cortemaderainn.com/wp-content/uploads/2013/03/rms_1.jpg"],
  [3, "Superior King Guest Room", "Our superior level rooms feature one king size bed and either a patio or balcony opening out towards our courtyard and pool area.", "https://www.cortemaderainn.com/wp-content/uploads/2013/03/DSC_6383.jpg"],
  [3, "Deluxe Two-Bedded Guest Room", "Located in our Garden Building, our deluxe level two bedded rooms offer one queen and one extra long full bed. All of these spacious and beautifully appointed guest rooms feature either a patio or balcony.", "https://www.cortemaderainn.com/wp-content/uploads/2013/03/DSC_6778.jpg"],
  [3, "Superior Two-Bedded Room", "Superior level two bedded guest rooms feature two extra long full size beds as well as a second vanity outside the bathroom area. These rooms offer a view of the courtyard and pool area.", "https://www.cortemaderainn.com/wp-content/uploads/2013/03/DSC_6857.jpg"]
]

room_type_list.each do |h_id, type, description, link|
	RoomType.create(hotel_id: h_id, type_: type, description: description, picture_link: link)
end

